/**
 * Open a printable HTML report for a scan record.
 */
export function printScanReport(scan) {
  const win = window.open('', '_blank', 'noopener,noreferrer');
  if (!win) {
    alert('Allow pop-ups to export/print the report.');
    return;
  }

  const date = new Date(scan.timestamp).toLocaleString();
  const conf = Math.round((scan.confidence || 0) * 100);
  const patient = scan.patientId ? `<tr><th>Case ID</th><td>${escapeHtml(scan.patientId)}</td></tr>` : '';
  const heatmap = scan.heatmap
    ? `<figure><figcaption>Grad-CAM activation map</figcaption><img src="${scan.heatmap}" alt="Heatmap" style="max-width:100%;height:auto;border:1px solid #e2e8f0;border-radius:8px"/></figure>`
    : '';
  const preview = scan.previewUrl
    ? `<figure><figcaption>Source slice</figcaption><img src="${scan.previewUrl}" alt="Source" style="max-width:100%;height:auto;border:1px solid #e2e8f0;border-radius:8px"/></figure>`
    : '';

  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"/><title>CerebroAI Report — ${escapeHtml(scan.fileName)}</title>
<style>
  body{font-family:system-ui,sans-serif;color:#0f172a;padding:32px;max-width:720px;margin:0 auto;line-height:1.5}
  h1{font-size:1.25rem;margin:0 0 4px} .meta{color:#64748b;font-size:12px;margin-bottom:24px}
  table{width:100%;border-collapse:collapse;margin:16px 0;font-size:14px}
  th,td{border:1px solid #e2e8f0;padding:8px 12px;text-align:left} th{background:#f8fafc;width:140px}
  .banner{background:#fffbeb;border:1px solid #fde68a;padding:12px;border-radius:8px;font-size:12px;margin-top:24px}
  figure{margin:16px 0} figcaption{font-size:11px;color:#64748b;margin-bottom:6px;text-transform:uppercase;letter-spacing:.05em}
  @media print{body{padding:16px}}
</style></head><body>
  <h1>CerebroAI — Screening Report</h1>
  <p class="meta">Generated ${date} · Research &amp; education only</p>
  <table>
    <tr><th>File</th><td>${escapeHtml(scan.fileName)}</td></tr>
    ${patient}
    <tr><th>Prediction</th><td><strong>${escapeHtml(scan.prediction)}</strong></td></tr>
    <tr><th>Confidence</th><td>${conf}%</td></tr>
    <tr><th>Severity</th><td>${escapeHtml(scan.severity || '—')}</td></tr>
  </table>
  <h2>Findings</h2><p>${escapeHtml(scan.findings || '—')}</p>
  <h2>Recommendation</h2><p>${escapeHtml(scan.recommendation || '—')}</p>
  ${preview}${heatmap}
  <div class="banner"><strong>Not for clinical use.</strong> This report is generated by an AI screening tool and must not replace radiologist or physician interpretation.</div>
  <script>window.onload=function(){window.print()}</script>
</body></html>`);
  win.document.close();
}

export function downloadSessionJson(history, auditLog) {
  const payload = {
    exportedAt: new Date().toISOString(),
    app: 'CerebroAI',
    version: '1.3.0',
    history,
    auditLog,
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `cerebroai-session-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
